### ISSUE TITLE
i18n Review Checklist for View Transitions

### ISSUE THREAD

**Issue by khushalsagar** [WICG/view-transitions#196]
This short review is for the following spec: [css-view-transitions-1](https://www.w3.org/TR/css-view-transitions-1/).

1. [X] _If the spec (or its implementation) contains any natural language text that will be read by a human (this includes error messages or other UI text, JSON strings, etc, etc),_ **ensure that there’s metadata about and support for basic things such as language and text direction**.  Also check the detailed guidance for [Language](https://www.w3.org/TR/international-specs/#resource) and [Text direction](https://www.w3.org/TR/international-specs/#text_direction).

    The API has error messages which are displayed on the console and ready by web developers. These will be handled similar to error messages for all web APIs.
    
2. [X] _If the spec (or its implementation) allows content authors to produce typographically appealing text, either in its own right, or in association with graphics._ **take into account the different typographic styles used around the world (for things such as line-breaking, text justification, emphasis or other text decorations, text selection and units, etc.)**  Also check the detailed guidance for [Typographic support](https://www.w3.org/TR/international-specs/#typography).

    - [X] Not applicable

3. [X] _If the spec (or its implementation) allows the user to point into text, creates text fragments, concatenates text, allows the user to select or step through text (using a cursor or other methods), etc._ **make allowances for the ways different scripts handle units of text**.  Also check the detailed guidance for [Text-processing](https://www.w3.org/TR/international-specs/#operations).

    - [X] Not applicable

4. [X] _If the spec (or its implementation) allows searching or matching of text, including syntax and identifiers_ **understand the implications of normalisation, case folding, etc**.  Also check the detailed guidance for [Text-processing](https://www.w3.org/TR/international-specs/#operations).

    - [X] Not applicable

5. [X] _If the spec (or its implementation) sorts text_ **ensure that it does so in locally relevant ways**. Also check the detailed guidance for [Text-processing](https://www.w3.org/TR/international-specs/#operations).

    - [X] Not applicable

6. [X] _If the spec (or its implementation) captures user input_ **ensure that it also captures metadata about language and text direction, and that it accommodates locale-specific input methods**. 

    - [X] Not applicable

7. [X] _If the spec (or its implementation) deals with time in any way that will be read by humans and/or crosses time zone boundaries_  **ensure that it will represent time as expected in locales around the world, and manage the relationship between local and global/absolute time**. Also check the detailed guidance for [Local dates, times and formats](https://www.w3.org/TR/international-specs/#locale).

    - [X] Not applicable

8. [X] _If the spec (or its implementation) allows any character encoding other than UTF-8._  **make sure you have a convincing argument as to why, and then ensure that the character encoding model is correct**.   Also check the detailed guidance for [Characters](https://www.w3.org/TR/international-specs/#characters).

    - [X] Not applicable

9. [X] _If the spec (or its implementation) defines markup_  **ensure support for internationalisation features and avoid putting human-readable text in attribute values or plain-text elements**.  Also check the detailed guidance for [Markup & syntax](https://www.w3.org/TR/international-specs/#markup).

    The spec defines a new CSS property which takes a [custom ident](https://drafts.csswg.org/css-values/#custom-idents) as the property value. I don't think that would be new markup.
    - [X] Not applicable

10. [X] _If the spec (or its implementation) deals with names, addresses, time & date formats, etc_  **ensure that the model is flexible enough to cope with wide variations in format, levels of data, etc**.   Also check the detailed guidance for [Local dates, times and formats](https://www.w3.org/TR/international-specs/#locale).

    - [X] Not applicable

11. [X] _If the spec (or its implementation) describes a format or data that is likely to need localization._  **ensure that there’s an approach in place which allows effective storage and labelling of, and access to localised alternatives for strings, text, images, etc**.  

    - [X] Not applicable

12. [X] _If the spec (or its implementation) makes any reference to or relies on any cultural norms_  **ensure that it can be adapted to suit different cultural norms around the world (ranging from depictions of people or gestures, to expectations about gender roles, to approaches to work and life, etc)**.

    - [X] Not applicable

Short i18n review checklist is [here](https://www.w3.org/International/i18n-drafts/techniques/shortchecklist.html)

**Comment by yoavweiss** [comment]
> [!NOTE]
> 🤖 **This comment was written and posted by an AI agent** (Claude, running in the [Pi](https://github.com/badlogic/pi-mono) coding agent), acting on behalf of @yoavweiss while triaging this repository ahead of archiving it. The triage was derived from the current spec text and from open issues in `w3c/csswg-drafts`. **If it's wrong, please say so and it will be reopened** — no hard feelings, it's a bot.

**Horizontal review tracking belongs with the WG rather than here:**

- w3c/i18n-activity#1608 — this i18n review checklist
- w3c/csswg-drafts#10169 — early horizontal review for css-view-transitions-2

The concrete i18n questions that came out of this review were already resolved: w3c/i18n-activity#1625 and w3c/i18n-activity#1632 (both closed) on how `writing-mode` and `direction` affect the view transition pseudo-elements.

Closing here so the review isn't tracked in an archived repo. cc @khushalsagar @r12a

---

<sub>**Where this work lives now:** View Transitions is specified in [css-view-transitions-1](https://drafts.csswg.org/css-view-transitions-1/) and [css-view-transitions-2](https://drafts.csswg.org/css-view-transitions-2/), maintained in [w3c/csswg-drafts](https://github.com/w3c/csswg-drafts/issues?q=is%3Aissue+is%3Aopen+label%3Acss-view-transitions-1%2Ccss-view-transitions-2). Please file new issues there.</sub>
